### ISSUE TITLE
`run` and `shell` commands should set up request

### ISSUE THREAD

**Issue by davisagli** [ericof/plonectl#5]
They should do something like:
```
from Testing.makerequest import makerequest
from zope.globalrequest import setRequest

app = makerequest(app)
setRequest(app.REQUEST)
```

**Comment by davisagli** [comment]
Ah, looks like `run` does but `shell` doesn't? On the other hand, `shell` sets the site hook but `run` doesn't. I think they should work similarly.

**Comment by ericof** [comment]
@davisagli Both should set the request, as they call `plonectl.utils.app.get_app`.
Could you provide me with an example that does not work?

**Comment by davisagli** [comment]
@ericof I must have been confused yesterday, seems to be working now.
